---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
