---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  source:
    repoURL: https://github.com/mazhdrak/EKS-Platform-Showcase.git
    targetRevision: main
    path: apps/demo-service/deploy/overlays/local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    # HPA owns replicas; do not fight it on every sync.
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
